baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Hydroquo+'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/hydorquo_logo.png"
  desktop: "images/logo/hydorquo_logo.png"
  desktop_height: "36px"
footer:
  copyright_text: 'Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Hydroquo+"
  meta_og_type: "website"
  meta_og_url: "https://hydroquo.com"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "Hydroquo+ is a technology company which aims to solve global water challenges through innovative applications of modern technology"
  #meta_twitter_card: "summary"
  #meta_twitter_site: "@zerostaticio"
  #meta_twitter_creator: "@zerostaticio"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
